package com.example.smsbackend.dto;

import com.fasterxml.jackson.annotation.JsonAlias;
import java.util.List;

public record DeviceProtocolSettings(
    List<DeviceContactSettings> contacts,
    String imei,
    String eviewVersion,
    String contactNumber,
    Integer contactSlot,
    Boolean contactSmsEnabled,
    Boolean contactCallEnabled,
    String contactName,
    String smsPassword,
    Boolean smsWhitelistEnabled,
    Boolean requestLocation,
    Boolean requestGpsLocation,
    Boolean requestLbsLocation,
    @JsonAlias({"wifi_enabled", "wifiPositioning", "wifi_positioning"})
    String wifiEnabled,
    Boolean bluetoothEnabled,
    Integer micVolume,
    Integer speakerVolume,
    Boolean vibrationEnabled,
    Boolean beepEnabled,
    Boolean prefixEnabled,
    String prefixName,
    Boolean checkBattery,
    Integer sosMode,
    Integer sosActionTime,
    String sosCallRingTime,
    String sosCallTalkTime,
    Boolean fallDownEnabled,
    Integer fallDownSensitivity,
    Boolean fallDownCall,
    Boolean noMotionEnabled,
    String noMotionTime,
    Boolean noMotionCall,
    Boolean motionEnabled,
    String motionStaticTime,
    String motionDurationTime,
    Boolean motionCall,
    Boolean overSpeedEnabled,
    String overSpeedLimit,
    Boolean geoFenceEnabled,
    Integer geoFenceMode,
    String geoFenceRadius,
    Boolean apnEnabled,
    String apn,
    Boolean serverEnabled,
    String serverHost,
    Integer serverPort,
    Boolean gprsEnabled,
    String workingMode,
    String workingModeInterval,
    String workingModeNoMotionInterval,
    String continuousLocateInterval,
    String continuousLocateDuration,
    String timeZone,
    Boolean turnOffDevice,
    Boolean findMyDevice,
    Boolean heartRateEnabled,
    String heartRateInterval,
    Boolean stepDetectionEnabled,
    String stepDetectionInterval,
    Boolean checkStatus,
    @JsonAlias({"authorized_numbers", "whitelistedNumbers", "whitelisted_numbers"})
    List<String> authorizedNumbers,
    @JsonAlias("geo_fences")
    List<GeoFenceSetting> geoFences
) {
}
